# Generated by Django 5.1.2 on 2024-12-22 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='course',
        ),
    ]
